# Reusable workflow for releases; to eject, you can replace this file with
name: Release
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
      - name: publish
        run: npm publish
        secrets:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}